// frontend/src/services/blueprintService.ts
import apiClient from './api';
import { Blueprint } from '../types';

// Define the input type, omitting fields generated by the backend
interface CreateBlueprintData {
    name: string;
    description?: string;
    git_repo_url: string;
}
interface UpdateBlueprintData {
  name?: string;
  description?: string;
  git_repo_url?: string;
}
const listBlueprints = async (): Promise<Blueprint[]> => {
  try {
    const response = await apiClient.get<Blueprint[]>('/blueprints');
    return response.data;
  } catch (error: any) {
    console.error("Error fetching blueprints:", error);
    // Re-throw or handle error as needed
    throw error;
  }
};

// Add create, getById, update, delete, parse functions later
const getBlueprintById = async (id: string): Promise<Blueprint> => {
    try {
        const response = await apiClient.get<Blueprint>(`/blueprints/${id}`);
        return response.data;
    } catch (error: any) {
         console.error(`Error fetching blueprint ${id}:`, error);
         throw error; // Re-throw to be caught by the component
    }
}

const parseBlueprint = async (id: string): Promise<any> => { // Return type might be more specific
    const response = await apiClient.post(`/blueprints/${id}/parse`);
    return response.data;
}

const createBlueprint = async (data: CreateBlueprintData): Promise<Blueprint> => {
    try {
        const response = await apiClient.post<Blueprint>('/blueprints', data);
        return response.data;
    } catch (error: any) {
         console.error("Error creating blueprint:", error);
         // Re-throw with potentially better error message if needed
         throw error;
    }
};

const deleteBlueprint = async (id: string): Promise<void> => {
    await apiClient.delete(`/blueprints/${id}`);
}
const updateBlueprint = async (id: string, data: UpdateBlueprintData): Promise<Blueprint> => {
  try {
      // Use PUT method for updates
      const response = await apiClient.put<Blueprint>(`/blueprints/${id}`, data);
      return response.data;
  } catch (error: any) {
       console.error(`Error updating blueprint ${id}:`, error);
       throw error; // Re-throw
  }
};


const blueprintService = {
  listBlueprints,
  getBlueprintById,
  parseBlueprint,
  createBlueprint,
  deleteBlueprint,
  updateBlueprint
};

export default blueprintService;